### ISSUE TITLE
The conditionalization of impl-lispworks-condition-variables needs to be improve

### ISSUE THREAD

**Issue by Yehouda** [sionescu/bordeaux-threads#31]
The impl-lispworks-condition-variables is conditionalized in bordeaux-threads.asd, it will be broken
 in LW 8 and later versions.

It should should be #+(or lispworks5 lispworks4), then it will work with all future versions.

**Comment by sionescu** [comment]
Done, thank you.

**Comment by Yehouda** [comment]
There are still wrong conditionalizations in impl-lispworks.lisp, specifically these:
;;;;;;;;;;;;;;;;;;;;

#+(or lispworks6 lispworks7)
(defun make-condition-variable (&key name)
  (mp:make-condition-variable :name (or name "Anonymous condition variable")))

#+(or lispworks6 lispworks7)
(defun condition-wait (condition-variable lock &key timeout)
  (mp:condition-variable-wait condition-variable lock :timeout timeout)
  t)

#+(or lispworks6 lispworks7)
(defun condition-notify (condition-variable)
  (mp:condition-variable-signal condition-variable))
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

These definition need to be conditionalized by   #-(or lispworks4 lispworks5) , so they continue
to work in future LispWorks releases.
